--FORMAT DATE
SELECT
	Date,
	FORMAT(Date, 'dddd') AS [Day]
FROM Sales;


--ADD A NEW COLUMN DAY

ALTER TABLE Sales
ADD Day VARCHAR(50);



--UPDATE THE TABLE SALES AFTER FORMAT

UPDATE Sales
SET Day = FORMAT(Date, 'dddd')

--CHANGE DATA TYPE FOR USA_DATE COLUMN FROM VARCHAR TO DATE

SELECT CONVERT(DATE, USA_Date, 23) AS New
FROM Sales
