-- FIND THE TOTAL NUMBER OF ORDERS
-- FIND THE TOTAL NUMBER OF ORDERS FOR EACH PRODUCT
-- FIND THE TOTAL NUMBER OF ORDERS FOR EACH DAY
-- FIND THE TOTAL NUMBER OF ORDERS BY PURCHASE TYPE
-- FIND THE TOTAL NUMBER OF ORDERS FOR EACH CITY
-- ADDITIONALLY PROVIDE DETAILS SUCH AS ORDER ID, ORDER DATE

SELECT
	OrderID,
	Date,
	Product,
	Day,
	City,
	PurchaseType,
	COUNT(*) OVER() [Total Orders],
	COUNT(*) OVER(PARTITION BY Product) [Orders by Product],
	COUNT(*) OVER(PARTITION BY Day) [Orders by Day],
	COUNT(*) OVER(PARTITION BY PurchaseType) [Orders by PurchaseType],
	COUNT(*) OVER(PARTITION BY City) [Orders by City]
FROM Sales;

SELECT
TOP 5*
FROM Sales